### PR TITLE
Resolves relative path issue on Windows

### LINKED ISSUE #19: Path for config.json is not resolved in scanner.py
The relative path of `config.json` is not resolved in `scanner.py` [Reproducible in Windows only]

```python
try:
    with open(file_path('../config.json')) as config_file:
        config = json.load(config_file)
```

Reported by @Kashish121

### PR DESCRIPTION
**Pull request by vinitshahdeo**
Fixes #19 

@Kashish121

- Please review this PR.
- Please checkout to `feature/relative-path-bug` branch and test the e2e flow.

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@Kashish121 There's another minor change in this PR: Moved the `scanner_thread.py` in a separate folder.

**Comment by vinitshahdeo** [comment]
@Kashish121 Invited you as a collaborator, please check your email and accept the invitation.

**Comment by Kashish121** [comment]
Thank You for adding me as a collaborator. Accepted the invitation. :star2:

**Comment by vinitshahdeo** [comment]
@Kashish121 Merging this into `develop`.
Thanks for reviewing.

**Pull request merged**
