### PR TITLE
Solves issue #1 and modernizes for Python 3.8

### PR DESCRIPTION
**Pull request by tinovasq**
The goal for this was originally just to solve the hard coding issue mentioned in issue #1, but I noticed that it wouldn't compile with my python install, so I made the necessary (small) syntax changes to get it working with the modern release. Everything should still work as intended! Cheers.

### CODE REVIEW

**Comment by vinitshahdeo** [comment]
@Kashish121 Have a look into this. 👁️

**Comment by Kashish121** [comment]
@vinitshahdeo The changes are appropriate. Runs fine, no issues.

**Comment by vinitshahdeo** [comment]
@Kashish121 Thanks for your confirmation. 🎉

**Comment by tinovasq** [comment]
Thanks guys! Glad to be of assistance, let me know if you need anything done at any point down the line, I am always happy to help!

**Comment by vinitshahdeo** [comment]
@tinovasq, Sure thing!

**Pull request merged**
