### PR TITLE
Port Scanner Component

### LINKED ISSUE #121: Port Scanner Form Component in React
As we've built many features to justify the one-liner description of this project i.e. a go-to networking tool, now it's time to revamp the existing UI.  

Add a new component `PortScannerForm.js` which will take inputs for:

- host to scan
- lower range of ports
- upper range of ports

This component should also have a button called `SCAN`. The scanning for open ports will start on clicking this button. Refer the image attached below for design

_As of now, on clicking `SCAN` button, the values in the input fields should be displayed in console_

P.S. : The basic frontend on react is available on `feature/frontend-react` branch in the folder `network-scanner`. Add your components in the same branch. Do not make any changes in `App.js` / `index.js`.  

image

### PR DESCRIPTION
**Pull request by devRawnie**
# Description

Please include a summary of the change and which issue is fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
Created a new PortScanner Form Component as per the given design. Also added logic for validation of the inputs.

Fixes #121 

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added all the three reviewers: @vinitshahdeo, @kashish121 & @ishika1727

### CODE REVIEW

**Review by ishika1727 — CHANGES_REQUESTED** [review]
@devRawnie Some changes:

1. Please remove the css from `index.css`. Instead create a file `portscanner.css` in a new folder called `css` and put the styling in it.
2. Do not commit any changes in App.js. Revert it back the way it initially was.

**Comment by devRawnie** [comment]
Sure, doing that right away.

**Comment by devRawnie** [comment]
I have committed the new changes as per the requirements. Kindly go through the same

**Comment by ishika1727** [comment]
Good to go. 👍

**Review by ishika1727 — APPROVED** [review]

**Pull request merged**
