### PR TITLE
Feature/documentation

### LINKED ISSUE #62: [Documentation]Update working of the project in docs
Analyze the complete working of the project and update the documentation in `docs/Documentation.docx` and `docs/documentation.md`.

Create a PR in  `feature/documentation` branch.

> Good to have a video demonstrating the working of the project

### PR DESCRIPTION
**Pull request by SSHREYA71**
## Description

Updated the documentation.
organized the information in an ordered list
Added screenshots of the code

Fixes #62

## Type of change

- [x] This change requires a documentation update
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added all the three reviewers: @vinitshahdeo, @kashish121 & @ishika1727

### CODE REVIEW

**Comment by Kashish121** [comment]
@SSHREYA71, a few notes here:
1. You need not create a new file(`NewDocumentation.md`). It would be better if you make changes in `documentation.md` itself.
2. For the images that you have uploaded(index.js.png, ports.png, randomnm.js.png, scanner.py.png) in `PortScanner/docs`, you can move them to `PortScanner/assets` folder.
3. Consider adding steps for mainScanner.py as well as ipscanner.py .

**Review by Kashish121 — CHANGES_REQUESTED** [review]
@SSHREYA71, a few notes here:
1. You need not create a new file(`NewDocumentation.md`). It would be better if you make changes in `documentation.md` itself.
2. For the images that you have uploaded(index.js.png, ports.png, randomnm.js.png, scanner.py.png) in `PortScanner/docs`, you can move them to `PortScanner/assets` folder.
3. Consider adding steps for mainScanner.py as well as ipscanner.py .

Great work otherwise! 💯

**Comment by SSHREYA71** [comment]
> @SSHREYA71, a few notes here:
> 
> 1. You need not create a new file(`NewDocumentation.md`). It would be better if you make changes in `documentation.md` itself.
> 2. For the images that you have uploaded(index.js.png, ports.png, randomnm.js.png, scanner.py.png) in `PortScanner/docs`, you can move them to `PortScanner/assets` folder.
> 3. Consider adding steps for mainScanner.py as well as ipscanner.py .
> 
> Great work otherwise! 💯

Noted, I Will make the changes soon. And thank you :)

**Comment by Kashish121** [comment]
@SSHREYA71 any update?

**Comment by SSHREYA71** [comment]
> @SSHREYA71 any update?

I am getting errors in running the scanner. I am trying. before the end of this week, I will hopefully make the changes suggested.

**Comment by SSHREYA71** [comment]
I have made the changes requested, please review and let me know :) @Kashish121 @ishika1727

**Comment by SSHREYA71** [comment]
@vinitshahdeo please review this its pending for 15 days now.

**Review by vinitshahdeo — APPROVED** [review]

**Pull request merged**
