### PR TITLE
Completed History Component

### LINKED ISSUE #155: History component in React
As we've built many features to justify the one-liner description of this project i.e. a go-to networking tool, now it's time to revamp the existing UI.  

Add a new component `History.js` which will display the details of last 10 scans.  Refer the image attached below for design.

_As of now, create the `History.js` which takes its data of last 10 scans from a json file `scans.json`(create a json file with harcoded data for last 10 scans) and displays according to the given UI_

P.S. : The basic frontend on react is available on `feature/frontend-react` branch in the folder `network-scanner`. Add your components in the same branch. Do not make any changes in `App.js` / `index.js`.  

image

### PR DESCRIPTION
**Pull request by devRawnie**
# Description

Created a new History.js Component, as per the template provided in the issue description. The component imports a hard-coded json object from the src/shared/ folder and displays the object in tabular form.
Image of the Component
Image of the JSON file

Fixes #155 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added all the three reviewers: @vinitshahdeo, @kashish121 & @ishika1727

### CODE REVIEW

**Comment by devRawnie** [comment]
Completed the History.js component. Kindly go through the same.

**Review by vinitshahdeo — COMMENTED** [review]
@devRawnie Can you please attach the screenshots in the PR description?

**Comment by devRawnie** [comment]
I attached the screeshots. Kindly check

**Comment by devRawnie** [comment]
Hi, If everything is fine with this PULL REQUEST kindly merge the same

**Review by vinitshahdeo — COMMENTED** [review]
@ishika1727 Can you please review and close the PR, it's pending since long?

**Comment by devRawnie** [comment]
Hi, It has been more than 15 days. since I have completed the code for this module. Kindly check the same and merge the PR

**Comment by devRawnie** [comment]
@vinitshahdeo Been more than a month since I created this PR. If it is not ready to merge kindly tell me the changes , or else please merge the same. @ishika1727

**Review by ishika1727 — APPROVED** [review]
@devRawnie Sorry for the delay. The code is good. Merging the PR.

**Pull request merged**
