### PR TITLE
added about.html

### PR DESCRIPTION
**Pull request by flyingsonu122**
# Description
added about.html

Fixes # (issue)
#135 

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added all the three reviewers: @vinitshahdeo, @kashish121 & @ishika1727

### CODE REVIEW

**Comment by flyingsonu122** [comment]
@Kashish121 please have a look

**Comment by Kashish121** [comment]
@flyingsonu122 the `develop` branch has recently been merged with few commits. It would be nice if you sync up your fork with original repository and create a PR again.

> This is to avoid the first 5 commits included in this PR, which is not related to this PR/Issue.

**Comment by flyingsonu122** [comment]
> @flyingsonu122 the `develop` branch has recently been merged with few commits. It would be nice if you sync up your fork with original repository and create a PR again.
> 
> > This is to avoid the first 5 commits included in this PR, which is not related to this PR/Issue.

okay, working on it

**Comment by flyingsonu122** [comment]
@Kashish121 @vinitshahdeo added a new PR #142 

please look into it

**Pull request closed without merging**
