### PR TITLE
 added logos

### LINKED ISSUE #28: [DESIGN] Logo required
> A logo has a significant impact on a project's public perception. Logo grabs attention and makes a strong first impression and a foundation of the brand/project identity.

Since [this](https://github.com/vinitshahdeo/PortScanner) project has no logo, **design a good, formal, attractive and elegant logo for this project that stands for our objective and relates to the project identity. i.e. a go-to networking tool for scanning the networks.**

- Export in all formats with different standard dimensions.

    - `PNG`
    - `SVG`
    - `JPG`

- Design `favicon` for the same. 
- Update the raw formats to the `assets/raw` folder.

**Please discuss here before submitting a PR.** Share your design idea here you've got one for the logo.

### PR DESCRIPTION
**Pull request by Sukran001**
Added logos.
Fixes #28

### CODE REVIEW

**Comment by Sukran001** [comment]
@Kashish121 do you want me to add all the anchor logos? Like I have made 5 anchor logos and added 2 of them already. So, do you want me to add the other 3 logos too?
@vinitshahdeo do you want me to export both .png and .jpg format of all the designs in the folder?

**Comment by vinitshahdeo** [comment]
@Sukran001 Yes, please export both. It'll be great if you submit `.svg` too. Basically this folder will contain all the media assets.

**Comment by Kashish121** [comment]
@Sukran001 would be better if you add others too.

**Comment by Sukran001** [comment]
@Kashish121 I have updated the other anchor logos in the same .ai file. 
@vinitshahdeo Do you really want me to add 3 formats of the logos? As currently i supplied 8 logos. So if I create 3 formats for each logo there will be 24 files. It may become cluttered.

**Comment by Kashish121** [comment]
@Sukran001 Thank you for your patience :)
And we can work with **.ai** file. No need to upload **.png** or **.jpg** .

**Review by Kashish121 — APPROVED** [review]

**Pull request merged**
